/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = SpaceTraders.Generated.Client.OpenAPIDateConverter;

namespace SpaceTraders.Generated.Model
{
    /// <summary>
    /// The terms to fulfill the contract.
    /// </summary>
    [DataContract(Name = "ContractTerms")]
    public partial class ContractTerms
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ContractTerms" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ContractTerms() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ContractTerms" /> class.
        /// </summary>
        /// <param name="deadline">The deadline for the contract. (required).</param>
        /// <param name="payment">payment (required).</param>
        /// <param name="deliver">The cargo that needs to be delivered to fulfill the contract..</param>
        public ContractTerms(DateTimeOffset deadline = default, ContractPayment payment = default, List<ContractDeliverGood> deliver = default)
        {
            this.Deadline = deadline;
            // to ensure "payment" is required (not null)
            if (payment == null)
            {
                throw new ArgumentNullException("payment is a required property for ContractTerms and cannot be null");
            }
            this.Payment = payment;
            this.Deliver = deliver;
        }

        /// <summary>
        /// The deadline for the contract.
        /// </summary>
        /// <value>The deadline for the contract.</value>
        [DataMember(Name = "deadline", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset Deadline { get; set; }

        /// <summary>
        /// Gets or Sets Payment
        /// </summary>
        [DataMember(Name = "payment", IsRequired = true, EmitDefaultValue = true)]
        public ContractPayment Payment { get; set; }

        /// <summary>
        /// The cargo that needs to be delivered to fulfill the contract.
        /// </summary>
        /// <value>The cargo that needs to be delivered to fulfill the contract.</value>
        [DataMember(Name = "deliver", EmitDefaultValue = false)]
        public List<ContractDeliverGood> Deliver { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ContractTerms {\n");
            sb.Append("  Deadline: ").Append(Deadline).Append("\n");
            sb.Append("  Payment: ").Append(Payment).Append("\n");
            sb.Append("  Deliver: ").Append(Deliver).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
