/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = SpaceTraders.Generated.Client.OpenAPIDateConverter;

namespace SpaceTraders.Generated.Model
{
    /// <summary>
    /// CreateSurvey201ResponseData
    /// </summary>
    [DataContract(Name = "create_survey_201_response_data")]
    public partial class CreateSurvey201ResponseData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateSurvey201ResponseData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateSurvey201ResponseData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateSurvey201ResponseData" /> class.
        /// </summary>
        /// <param name="cooldown">cooldown (required).</param>
        /// <param name="surveys">Surveys created by this action. (required).</param>
        public CreateSurvey201ResponseData(Cooldown cooldown = default, List<Survey> surveys = default)
        {
            // to ensure "cooldown" is required (not null)
            if (cooldown == null)
            {
                throw new ArgumentNullException("cooldown is a required property for CreateSurvey201ResponseData and cannot be null");
            }
            this.Cooldown = cooldown;
            // to ensure "surveys" is required (not null)
            if (surveys == null)
            {
                throw new ArgumentNullException("surveys is a required property for CreateSurvey201ResponseData and cannot be null");
            }
            this.Surveys = surveys;
        }

        /// <summary>
        /// Gets or Sets Cooldown
        /// </summary>
        [DataMember(Name = "cooldown", IsRequired = true, EmitDefaultValue = true)]
        public Cooldown Cooldown { get; set; }

        /// <summary>
        /// Surveys created by this action.
        /// </summary>
        /// <value>Surveys created by this action.</value>
        [DataMember(Name = "surveys", IsRequired = true, EmitDefaultValue = true)]
        public List<Survey> Surveys { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateSurvey201ResponseData {\n");
            sb.Append("  Cooldown: ").Append(Cooldown).Append("\n");
            sb.Append("  Surveys: ").Append(Surveys).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
