/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = SpaceTraders.Generated.Client.OpenAPIDateConverter;

namespace SpaceTraders.Generated.Model
{
    /// <summary>
    /// GetStatus200Response
    /// </summary>
    [DataContract(Name = "get_status_200_response")]
    public partial class GetStatus200Response
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetStatus200Response" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetStatus200Response() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetStatus200Response" /> class.
        /// </summary>
        /// <param name="status">The current status of the game server. (required).</param>
        /// <param name="varVersion">The current version of the API. (required).</param>
        /// <param name="resetDate">The date when the game server was last reset. (required).</param>
        /// <param name="description">description (required).</param>
        /// <param name="stats">stats (required).</param>
        /// <param name="leaderboards">leaderboards (required).</param>
        /// <param name="serverResets">serverResets (required).</param>
        /// <param name="announcements">announcements (required).</param>
        /// <param name="links">links (required).</param>
        public GetStatus200Response(string status = default, string varVersion = default, string resetDate = default, string description = default, GetStatus200ResponseStats stats = default, GetStatus200ResponseLeaderboards leaderboards = default, GetStatus200ResponseServerResets serverResets = default, List<GetStatus200ResponseAnnouncementsInner> announcements = default, List<GetStatus200ResponseLinksInner> links = default)
        {
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for GetStatus200Response and cannot be null");
            }
            this.Status = status;
            // to ensure "varVersion" is required (not null)
            if (varVersion == null)
            {
                throw new ArgumentNullException("varVersion is a required property for GetStatus200Response and cannot be null");
            }
            this.VarVersion = varVersion;
            // to ensure "resetDate" is required (not null)
            if (resetDate == null)
            {
                throw new ArgumentNullException("resetDate is a required property for GetStatus200Response and cannot be null");
            }
            this.ResetDate = resetDate;
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new ArgumentNullException("description is a required property for GetStatus200Response and cannot be null");
            }
            this.Description = description;
            // to ensure "stats" is required (not null)
            if (stats == null)
            {
                throw new ArgumentNullException("stats is a required property for GetStatus200Response and cannot be null");
            }
            this.Stats = stats;
            // to ensure "leaderboards" is required (not null)
            if (leaderboards == null)
            {
                throw new ArgumentNullException("leaderboards is a required property for GetStatus200Response and cannot be null");
            }
            this.Leaderboards = leaderboards;
            // to ensure "serverResets" is required (not null)
            if (serverResets == null)
            {
                throw new ArgumentNullException("serverResets is a required property for GetStatus200Response and cannot be null");
            }
            this.ServerResets = serverResets;
            // to ensure "announcements" is required (not null)
            if (announcements == null)
            {
                throw new ArgumentNullException("announcements is a required property for GetStatus200Response and cannot be null");
            }
            this.Announcements = announcements;
            // to ensure "links" is required (not null)
            if (links == null)
            {
                throw new ArgumentNullException("links is a required property for GetStatus200Response and cannot be null");
            }
            this.Links = links;
        }

        /// <summary>
        /// The current status of the game server.
        /// </summary>
        /// <value>The current status of the game server.</value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// The current version of the API.
        /// </summary>
        /// <value>The current version of the API.</value>
        [DataMember(Name = "version", IsRequired = true, EmitDefaultValue = true)]
        public string VarVersion { get; set; }

        /// <summary>
        /// The date when the game server was last reset.
        /// </summary>
        /// <value>The date when the game server was last reset.</value>
        [DataMember(Name = "resetDate", IsRequired = true, EmitDefaultValue = true)]
        public string ResetDate { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Stats
        /// </summary>
        [DataMember(Name = "stats", IsRequired = true, EmitDefaultValue = true)]
        public GetStatus200ResponseStats Stats { get; set; }

        /// <summary>
        /// Gets or Sets Leaderboards
        /// </summary>
        [DataMember(Name = "leaderboards", IsRequired = true, EmitDefaultValue = true)]
        public GetStatus200ResponseLeaderboards Leaderboards { get; set; }

        /// <summary>
        /// Gets or Sets ServerResets
        /// </summary>
        [DataMember(Name = "serverResets", IsRequired = true, EmitDefaultValue = true)]
        public GetStatus200ResponseServerResets ServerResets { get; set; }

        /// <summary>
        /// Gets or Sets Announcements
        /// </summary>
        [DataMember(Name = "announcements", IsRequired = true, EmitDefaultValue = true)]
        public List<GetStatus200ResponseAnnouncementsInner> Announcements { get; set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name = "links", IsRequired = true, EmitDefaultValue = true)]
        public List<GetStatus200ResponseLinksInner> Links { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetStatus200Response {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  ResetDate: ").Append(ResetDate).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Stats: ").Append(Stats).Append("\n");
            sb.Append("  Leaderboards: ").Append(Leaderboards).Append("\n");
            sb.Append("  ServerResets: ").Append(ServerResets).Append("\n");
            sb.Append("  Announcements: ").Append(Announcements).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
