/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = SpaceTraders.Generated.Client.OpenAPIDateConverter;

namespace SpaceTraders.Generated.Model
{
    /// <summary>
    /// PurchaseShipRequest
    /// </summary>
    [DataContract(Name = "purchase_ship_request")]
    public partial class PurchaseShipRequest
    {

        /// <summary>
        /// Gets or Sets ShipType
        /// </summary>
        [DataMember(Name = "shipType", IsRequired = true, EmitDefaultValue = true)]
        public ShipType ShipType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PurchaseShipRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PurchaseShipRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PurchaseShipRequest" /> class.
        /// </summary>
        /// <param name="shipType">shipType (required).</param>
        /// <param name="waypointSymbol">The symbol of the waypoint you want to purchase the ship at. (required).</param>
        public PurchaseShipRequest(ShipType shipType = default, string waypointSymbol = default)
        {
            this.ShipType = shipType;
            // to ensure "waypointSymbol" is required (not null)
            if (waypointSymbol == null)
            {
                throw new ArgumentNullException("waypointSymbol is a required property for PurchaseShipRequest and cannot be null");
            }
            this.WaypointSymbol = waypointSymbol;
        }

        /// <summary>
        /// The symbol of the waypoint you want to purchase the ship at.
        /// </summary>
        /// <value>The symbol of the waypoint you want to purchase the ship at.</value>
        [DataMember(Name = "waypointSymbol", IsRequired = true, EmitDefaultValue = true)]
        public string WaypointSymbol { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PurchaseShipRequest {\n");
            sb.Append("  ShipType: ").Append(ShipType).Append("\n");
            sb.Append("  WaypointSymbol: ").Append(WaypointSymbol).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
