/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = SpaceTraders.Generated.Client.OpenAPIDateConverter;

namespace SpaceTraders.Generated.Model
{
    /// <summary>
    /// The engine determines how quickly a ship travels between waypoints.
    /// </summary>
    [DataContract(Name = "ShipEngine")]
    public partial class ShipEngine
    {
        /// <summary>
        /// The symbol of the engine.
        /// </summary>
        /// <value>The symbol of the engine.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SymbolEnum
        {
            /// <summary>
            /// Enum ENGINEIMPULSEDRIVEI for value: ENGINE_IMPULSE_DRIVE_I
            /// </summary>
            [EnumMember(Value = "ENGINE_IMPULSE_DRIVE_I")]
            ENGINEIMPULSEDRIVEI = 1,

            /// <summary>
            /// Enum ENGINEIONDRIVEI for value: ENGINE_ION_DRIVE_I
            /// </summary>
            [EnumMember(Value = "ENGINE_ION_DRIVE_I")]
            ENGINEIONDRIVEI = 2,

            /// <summary>
            /// Enum ENGINEIONDRIVEII for value: ENGINE_ION_DRIVE_II
            /// </summary>
            [EnumMember(Value = "ENGINE_ION_DRIVE_II")]
            ENGINEIONDRIVEII = 3,

            /// <summary>
            /// Enum ENGINEHYPERDRIVEI for value: ENGINE_HYPER_DRIVE_I
            /// </summary>
            [EnumMember(Value = "ENGINE_HYPER_DRIVE_I")]
            ENGINEHYPERDRIVEI = 4
        }


        /// <summary>
        /// The symbol of the engine.
        /// </summary>
        /// <value>The symbol of the engine.</value>
        [DataMember(Name = "symbol", IsRequired = true, EmitDefaultValue = true)]
        public SymbolEnum Symbol { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ShipEngine" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ShipEngine() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ShipEngine" /> class.
        /// </summary>
        /// <param name="symbol">The symbol of the engine. (required).</param>
        /// <param name="name">The name of the engine. (required).</param>
        /// <param name="description">The description of the engine. (required).</param>
        /// <param name="condition">The repairable condition of a component. A value of 0 indicates the component needs significant repairs, while a value of 1 indicates the component is in near perfect condition. As the condition of a component is repaired, the overall integrity of the component decreases. (required).</param>
        /// <param name="integrity">The overall integrity of the component, which determines the performance of the component. A value of 0 indicates that the component is almost completely degraded, while a value of 1 indicates that the component is in near perfect condition. The integrity of the component is non-repairable, and represents permanent wear over time. (required).</param>
        /// <param name="speed">The speed stat of this engine. The higher the speed, the faster a ship can travel from one point to another. Reduces the time of arrival when navigating the ship. (required).</param>
        /// <param name="requirements">requirements (required).</param>
        /// <param name="quality">The overall quality of the component, which determines the quality of the component. High quality components return more ships parts and ship plating when a ship is scrapped. But also require more of these parts to repair. This is transparent to the player, as the parts are bought from/sold to the marketplace. (required).</param>
        public ShipEngine(SymbolEnum symbol = default, string name = default, string description = default, double condition = default, double integrity = default, int speed = default, ShipRequirements requirements = default, decimal quality = default)
        {
            this.Symbol = symbol;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ShipEngine and cannot be null");
            }
            this.Name = name;
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new ArgumentNullException("description is a required property for ShipEngine and cannot be null");
            }
            this.Description = description;
            this.Condition = condition;
            this.Integrity = integrity;
            this.Speed = speed;
            // to ensure "requirements" is required (not null)
            if (requirements == null)
            {
                throw new ArgumentNullException("requirements is a required property for ShipEngine and cannot be null");
            }
            this.Requirements = requirements;
            this.Quality = quality;
        }

        /// <summary>
        /// The name of the engine.
        /// </summary>
        /// <value>The name of the engine.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The description of the engine.
        /// </summary>
        /// <value>The description of the engine.</value>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// The repairable condition of a component. A value of 0 indicates the component needs significant repairs, while a value of 1 indicates the component is in near perfect condition. As the condition of a component is repaired, the overall integrity of the component decreases.
        /// </summary>
        /// <value>The repairable condition of a component. A value of 0 indicates the component needs significant repairs, while a value of 1 indicates the component is in near perfect condition. As the condition of a component is repaired, the overall integrity of the component decreases.</value>
        [DataMember(Name = "condition", IsRequired = true, EmitDefaultValue = true)]
        public double Condition { get; set; }

        /// <summary>
        /// The overall integrity of the component, which determines the performance of the component. A value of 0 indicates that the component is almost completely degraded, while a value of 1 indicates that the component is in near perfect condition. The integrity of the component is non-repairable, and represents permanent wear over time.
        /// </summary>
        /// <value>The overall integrity of the component, which determines the performance of the component. A value of 0 indicates that the component is almost completely degraded, while a value of 1 indicates that the component is in near perfect condition. The integrity of the component is non-repairable, and represents permanent wear over time.</value>
        [DataMember(Name = "integrity", IsRequired = true, EmitDefaultValue = true)]
        public double Integrity { get; set; }

        /// <summary>
        /// The speed stat of this engine. The higher the speed, the faster a ship can travel from one point to another. Reduces the time of arrival when navigating the ship.
        /// </summary>
        /// <value>The speed stat of this engine. The higher the speed, the faster a ship can travel from one point to another. Reduces the time of arrival when navigating the ship.</value>
        [DataMember(Name = "speed", IsRequired = true, EmitDefaultValue = true)]
        public int Speed { get; set; }

        /// <summary>
        /// Gets or Sets Requirements
        /// </summary>
        [DataMember(Name = "requirements", IsRequired = true, EmitDefaultValue = true)]
        public ShipRequirements Requirements { get; set; }

        /// <summary>
        /// The overall quality of the component, which determines the quality of the component. High quality components return more ships parts and ship plating when a ship is scrapped. But also require more of these parts to repair. This is transparent to the player, as the parts are bought from/sold to the marketplace.
        /// </summary>
        /// <value>The overall quality of the component, which determines the quality of the component. High quality components return more ships parts and ship plating when a ship is scrapped. But also require more of these parts to repair. This is transparent to the player, as the parts are bought from/sold to the marketplace.</value>
        [DataMember(Name = "quality", IsRequired = true, EmitDefaultValue = true)]
        public decimal Quality { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ShipEngine {\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Condition: ").Append(Condition).Append("\n");
            sb.Append("  Integrity: ").Append(Integrity).Append("\n");
            sb.Append("  Speed: ").Append(Speed).Append("\n");
            sb.Append("  Requirements: ").Append(Requirements).Append("\n");
            sb.Append("  Quality: ").Append(Quality).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
