/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = SpaceTraders.Generated.Client.OpenAPIDateConverter;

namespace SpaceTraders.Generated.Model
{
    /// <summary>
    /// ShipRefine201ResponseDataProducedInner
    /// </summary>
    [DataContract(Name = "Ship_Refine_201_Response_data_produced_inner")]
    public partial class ShipRefine201ResponseDataProducedInner
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShipRefine201ResponseDataProducedInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ShipRefine201ResponseDataProducedInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ShipRefine201ResponseDataProducedInner" /> class.
        /// </summary>
        /// <param name="tradeSymbol">Symbol of the good. (required).</param>
        /// <param name="units">Amount of units of the good. (required).</param>
        public ShipRefine201ResponseDataProducedInner(string tradeSymbol = default, int units = default)
        {
            // to ensure "tradeSymbol" is required (not null)
            if (tradeSymbol == null)
            {
                throw new ArgumentNullException("tradeSymbol is a required property for ShipRefine201ResponseDataProducedInner and cannot be null");
            }
            this.TradeSymbol = tradeSymbol;
            this.Units = units;
        }

        /// <summary>
        /// Symbol of the good.
        /// </summary>
        /// <value>Symbol of the good.</value>
        [DataMember(Name = "tradeSymbol", IsRequired = true, EmitDefaultValue = true)]
        public string TradeSymbol { get; set; }

        /// <summary>
        /// Amount of units of the good.
        /// </summary>
        /// <value>Amount of units of the good.</value>
        [DataMember(Name = "units", IsRequired = true, EmitDefaultValue = true)]
        public int Units { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ShipRefine201ResponseDataProducedInner {\n");
            sb.Append("  TradeSymbol: ").Append(TradeSymbol).Append("\n");
            sb.Append("  Units: ").Append(Units).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
