/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = SpaceTraders.Generated.Client.OpenAPIDateConverter;

namespace SpaceTraders.Generated.Model
{
    /// <summary>
    /// A mount is installed on the exterier of a ship.
    /// </summary>
    [DataContract(Name = "ShipMount")]
    public partial class ShipMount
    {
        /// <summary>
        /// Symbo of this mount.
        /// </summary>
        /// <value>Symbo of this mount.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SymbolEnum
        {
            /// <summary>
            /// Enum MOUNTGASSIPHONI for value: MOUNT_GAS_SIPHON_I
            /// </summary>
            [EnumMember(Value = "MOUNT_GAS_SIPHON_I")]
            MOUNTGASSIPHONI = 1,

            /// <summary>
            /// Enum MOUNTGASSIPHONII for value: MOUNT_GAS_SIPHON_II
            /// </summary>
            [EnumMember(Value = "MOUNT_GAS_SIPHON_II")]
            MOUNTGASSIPHONII = 2,

            /// <summary>
            /// Enum MOUNTGASSIPHONIII for value: MOUNT_GAS_SIPHON_III
            /// </summary>
            [EnumMember(Value = "MOUNT_GAS_SIPHON_III")]
            MOUNTGASSIPHONIII = 3,

            /// <summary>
            /// Enum MOUNTSURVEYORI for value: MOUNT_SURVEYOR_I
            /// </summary>
            [EnumMember(Value = "MOUNT_SURVEYOR_I")]
            MOUNTSURVEYORI = 4,

            /// <summary>
            /// Enum MOUNTSURVEYORII for value: MOUNT_SURVEYOR_II
            /// </summary>
            [EnumMember(Value = "MOUNT_SURVEYOR_II")]
            MOUNTSURVEYORII = 5,

            /// <summary>
            /// Enum MOUNTSURVEYORIII for value: MOUNT_SURVEYOR_III
            /// </summary>
            [EnumMember(Value = "MOUNT_SURVEYOR_III")]
            MOUNTSURVEYORIII = 6,

            /// <summary>
            /// Enum MOUNTSENSORARRAYI for value: MOUNT_SENSOR_ARRAY_I
            /// </summary>
            [EnumMember(Value = "MOUNT_SENSOR_ARRAY_I")]
            MOUNTSENSORARRAYI = 7,

            /// <summary>
            /// Enum MOUNTSENSORARRAYII for value: MOUNT_SENSOR_ARRAY_II
            /// </summary>
            [EnumMember(Value = "MOUNT_SENSOR_ARRAY_II")]
            MOUNTSENSORARRAYII = 8,

            /// <summary>
            /// Enum MOUNTSENSORARRAYIII for value: MOUNT_SENSOR_ARRAY_III
            /// </summary>
            [EnumMember(Value = "MOUNT_SENSOR_ARRAY_III")]
            MOUNTSENSORARRAYIII = 9,

            /// <summary>
            /// Enum MOUNTMININGLASERI for value: MOUNT_MINING_LASER_I
            /// </summary>
            [EnumMember(Value = "MOUNT_MINING_LASER_I")]
            MOUNTMININGLASERI = 10,

            /// <summary>
            /// Enum MOUNTMININGLASERII for value: MOUNT_MINING_LASER_II
            /// </summary>
            [EnumMember(Value = "MOUNT_MINING_LASER_II")]
            MOUNTMININGLASERII = 11,

            /// <summary>
            /// Enum MOUNTMININGLASERIII for value: MOUNT_MINING_LASER_III
            /// </summary>
            [EnumMember(Value = "MOUNT_MINING_LASER_III")]
            MOUNTMININGLASERIII = 12,

            /// <summary>
            /// Enum MOUNTLASERCANNONI for value: MOUNT_LASER_CANNON_I
            /// </summary>
            [EnumMember(Value = "MOUNT_LASER_CANNON_I")]
            MOUNTLASERCANNONI = 13,

            /// <summary>
            /// Enum MOUNTMISSILELAUNCHERI for value: MOUNT_MISSILE_LAUNCHER_I
            /// </summary>
            [EnumMember(Value = "MOUNT_MISSILE_LAUNCHER_I")]
            MOUNTMISSILELAUNCHERI = 14,

            /// <summary>
            /// Enum MOUNTTURRETI for value: MOUNT_TURRET_I
            /// </summary>
            [EnumMember(Value = "MOUNT_TURRET_I")]
            MOUNTTURRETI = 15
        }


        /// <summary>
        /// Symbo of this mount.
        /// </summary>
        /// <value>Symbo of this mount.</value>
        [DataMember(Name = "symbol", IsRequired = true, EmitDefaultValue = true)]
        public SymbolEnum Symbol { get; set; }
        /// <summary>
        /// Defines Deposits
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum DepositsEnum
        {
            /// <summary>
            /// Enum QUARTZSAND for value: QUARTZ_SAND
            /// </summary>
            [EnumMember(Value = "QUARTZ_SAND")]
            QUARTZSAND = 1,

            /// <summary>
            /// Enum SILICONCRYSTALS for value: SILICON_CRYSTALS
            /// </summary>
            [EnumMember(Value = "SILICON_CRYSTALS")]
            SILICONCRYSTALS = 2,

            /// <summary>
            /// Enum PRECIOUSSTONES for value: PRECIOUS_STONES
            /// </summary>
            [EnumMember(Value = "PRECIOUS_STONES")]
            PRECIOUSSTONES = 3,

            /// <summary>
            /// Enum ICEWATER for value: ICE_WATER
            /// </summary>
            [EnumMember(Value = "ICE_WATER")]
            ICEWATER = 4,

            /// <summary>
            /// Enum AMMONIAICE for value: AMMONIA_ICE
            /// </summary>
            [EnumMember(Value = "AMMONIA_ICE")]
            AMMONIAICE = 5,

            /// <summary>
            /// Enum IRONORE for value: IRON_ORE
            /// </summary>
            [EnumMember(Value = "IRON_ORE")]
            IRONORE = 6,

            /// <summary>
            /// Enum COPPERORE for value: COPPER_ORE
            /// </summary>
            [EnumMember(Value = "COPPER_ORE")]
            COPPERORE = 7,

            /// <summary>
            /// Enum SILVERORE for value: SILVER_ORE
            /// </summary>
            [EnumMember(Value = "SILVER_ORE")]
            SILVERORE = 8,

            /// <summary>
            /// Enum ALUMINUMORE for value: ALUMINUM_ORE
            /// </summary>
            [EnumMember(Value = "ALUMINUM_ORE")]
            ALUMINUMORE = 9,

            /// <summary>
            /// Enum GOLDORE for value: GOLD_ORE
            /// </summary>
            [EnumMember(Value = "GOLD_ORE")]
            GOLDORE = 10,

            /// <summary>
            /// Enum PLATINUMORE for value: PLATINUM_ORE
            /// </summary>
            [EnumMember(Value = "PLATINUM_ORE")]
            PLATINUMORE = 11,

            /// <summary>
            /// Enum DIAMONDS for value: DIAMONDS
            /// </summary>
            [EnumMember(Value = "DIAMONDS")]
            DIAMONDS = 12,

            /// <summary>
            /// Enum URANITEORE for value: URANITE_ORE
            /// </summary>
            [EnumMember(Value = "URANITE_ORE")]
            URANITEORE = 13,

            /// <summary>
            /// Enum MERITIUMORE for value: MERITIUM_ORE
            /// </summary>
            [EnumMember(Value = "MERITIUM_ORE")]
            MERITIUMORE = 14
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ShipMount" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ShipMount() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ShipMount" /> class.
        /// </summary>
        /// <param name="symbol">Symbo of this mount. (required).</param>
        /// <param name="name">Name of this mount. (required).</param>
        /// <param name="description">Description of this mount..</param>
        /// <param name="strength">Mounts that have this value, such as mining lasers, denote how powerful this mount&#39;s capabilities are..</param>
        /// <param name="deposits">Mounts that have this value denote what goods can be produced from using the mount..</param>
        /// <param name="requirements">requirements (required).</param>
        public ShipMount(SymbolEnum symbol = default, string name = default, string description = default, int strength = default, List<DepositsEnum> deposits = default, ShipRequirements requirements = default)
        {
            this.Symbol = symbol;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ShipMount and cannot be null");
            }
            this.Name = name;
            // to ensure "requirements" is required (not null)
            if (requirements == null)
            {
                throw new ArgumentNullException("requirements is a required property for ShipMount and cannot be null");
            }
            this.Requirements = requirements;
            this.Description = description;
            this.Strength = strength;
            this.Deposits = deposits;
        }

        /// <summary>
        /// Name of this mount.
        /// </summary>
        /// <value>Name of this mount.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Description of this mount.
        /// </summary>
        /// <value>Description of this mount.</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Mounts that have this value, such as mining lasers, denote how powerful this mount&#39;s capabilities are.
        /// </summary>
        /// <value>Mounts that have this value, such as mining lasers, denote how powerful this mount&#39;s capabilities are.</value>
        [DataMember(Name = "strength", EmitDefaultValue = false)]
        public int Strength { get; set; }

        /// <summary>
        /// Mounts that have this value denote what goods can be produced from using the mount.
        /// </summary>
        /// <value>Mounts that have this value denote what goods can be produced from using the mount.</value>
        [DataMember(Name = "deposits", EmitDefaultValue = false)]
        public List<ShipMount.DepositsEnum> Deposits { get; set; }

        /// <summary>
        /// Gets or Sets Requirements
        /// </summary>
        [DataMember(Name = "requirements", IsRequired = true, EmitDefaultValue = true)]
        public ShipRequirements Requirements { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ShipMount {\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Strength: ").Append(Strength).Append("\n");
            sb.Append("  Deposits: ").Append(Deposits).Append("\n");
            sb.Append("  Requirements: ").Append(Requirements).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
