/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = SpaceTraders.Generated.Client.OpenAPIDateConverter;

namespace SpaceTraders.Generated.Model
{
    /// <summary>
    /// Ship details.
    /// </summary>
    [DataContract(Name = "Ship")]
    public partial class Ship
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Ship" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Ship() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Ship" /> class.
        /// </summary>
        /// <param name="symbol">The globally unique identifier of the ship in the following format: &#x60;[AGENT_SYMBOL]-[HEX_ID]&#x60; (required).</param>
        /// <param name="registration">registration (required).</param>
        /// <param name="nav">nav (required).</param>
        /// <param name="crew">crew (required).</param>
        /// <param name="frame">frame (required).</param>
        /// <param name="reactor">reactor (required).</param>
        /// <param name="engine">engine (required).</param>
        /// <param name="cooldown">cooldown (required).</param>
        /// <param name="modules">Modules installed in this ship. (required).</param>
        /// <param name="mounts">Mounts installed in this ship. (required).</param>
        /// <param name="cargo">cargo (required).</param>
        /// <param name="fuel">fuel (required).</param>
        public Ship(string symbol = default, ShipRegistration registration = default, ShipNav nav = default, ShipCrew crew = default, ShipFrame frame = default, ShipReactor reactor = default, ShipEngine engine = default, Cooldown cooldown = default, List<ShipModule> modules = default, List<ShipMount> mounts = default, ShipCargo cargo = default, ShipFuel fuel = default)
        {
            // to ensure "symbol" is required (not null)
            if (symbol == null)
            {
                throw new ArgumentNullException("symbol is a required property for Ship and cannot be null");
            }
            this.Symbol = symbol;
            // to ensure "registration" is required (not null)
            if (registration == null)
            {
                throw new ArgumentNullException("registration is a required property for Ship and cannot be null");
            }
            this.Registration = registration;
            // to ensure "nav" is required (not null)
            if (nav == null)
            {
                throw new ArgumentNullException("nav is a required property for Ship and cannot be null");
            }
            this.Nav = nav;
            // to ensure "crew" is required (not null)
            if (crew == null)
            {
                throw new ArgumentNullException("crew is a required property for Ship and cannot be null");
            }
            this.Crew = crew;
            // to ensure "frame" is required (not null)
            if (frame == null)
            {
                throw new ArgumentNullException("frame is a required property for Ship and cannot be null");
            }
            this.Frame = frame;
            // to ensure "reactor" is required (not null)
            if (reactor == null)
            {
                throw new ArgumentNullException("reactor is a required property for Ship and cannot be null");
            }
            this.Reactor = reactor;
            // to ensure "engine" is required (not null)
            if (engine == null)
            {
                throw new ArgumentNullException("engine is a required property for Ship and cannot be null");
            }
            this.Engine = engine;
            // to ensure "cooldown" is required (not null)
            if (cooldown == null)
            {
                throw new ArgumentNullException("cooldown is a required property for Ship and cannot be null");
            }
            this.Cooldown = cooldown;
            // to ensure "modules" is required (not null)
            if (modules == null)
            {
                throw new ArgumentNullException("modules is a required property for Ship and cannot be null");
            }
            this.Modules = modules;
            // to ensure "mounts" is required (not null)
            if (mounts == null)
            {
                throw new ArgumentNullException("mounts is a required property for Ship and cannot be null");
            }
            this.Mounts = mounts;
            // to ensure "cargo" is required (not null)
            if (cargo == null)
            {
                throw new ArgumentNullException("cargo is a required property for Ship and cannot be null");
            }
            this.Cargo = cargo;
            // to ensure "fuel" is required (not null)
            if (fuel == null)
            {
                throw new ArgumentNullException("fuel is a required property for Ship and cannot be null");
            }
            this.Fuel = fuel;
        }

        /// <summary>
        /// The globally unique identifier of the ship in the following format: &#x60;[AGENT_SYMBOL]-[HEX_ID]&#x60;
        /// </summary>
        /// <value>The globally unique identifier of the ship in the following format: &#x60;[AGENT_SYMBOL]-[HEX_ID]&#x60;</value>
        [DataMember(Name = "symbol", IsRequired = true, EmitDefaultValue = true)]
        public string Symbol { get; set; }

        /// <summary>
        /// Gets or Sets Registration
        /// </summary>
        [DataMember(Name = "registration", IsRequired = true, EmitDefaultValue = true)]
        public ShipRegistration Registration { get; set; }

        /// <summary>
        /// Gets or Sets Nav
        /// </summary>
        [DataMember(Name = "nav", IsRequired = true, EmitDefaultValue = true)]
        public ShipNav Nav { get; set; }

        /// <summary>
        /// Gets or Sets Crew
        /// </summary>
        [DataMember(Name = "crew", IsRequired = true, EmitDefaultValue = true)]
        public ShipCrew Crew { get; set; }

        /// <summary>
        /// Gets or Sets Frame
        /// </summary>
        [DataMember(Name = "frame", IsRequired = true, EmitDefaultValue = true)]
        public ShipFrame Frame { get; set; }

        /// <summary>
        /// Gets or Sets Reactor
        /// </summary>
        [DataMember(Name = "reactor", IsRequired = true, EmitDefaultValue = true)]
        public ShipReactor Reactor { get; set; }

        /// <summary>
        /// Gets or Sets Engine
        /// </summary>
        [DataMember(Name = "engine", IsRequired = true, EmitDefaultValue = true)]
        public ShipEngine Engine { get; set; }

        /// <summary>
        /// Gets or Sets Cooldown
        /// </summary>
        [DataMember(Name = "cooldown", IsRequired = true, EmitDefaultValue = true)]
        public Cooldown Cooldown { get; set; }

        /// <summary>
        /// Modules installed in this ship.
        /// </summary>
        /// <value>Modules installed in this ship.</value>
        [DataMember(Name = "modules", IsRequired = true, EmitDefaultValue = true)]
        public List<ShipModule> Modules { get; set; }

        /// <summary>
        /// Mounts installed in this ship.
        /// </summary>
        /// <value>Mounts installed in this ship.</value>
        [DataMember(Name = "mounts", IsRequired = true, EmitDefaultValue = true)]
        public List<ShipMount> Mounts { get; set; }

        /// <summary>
        /// Gets or Sets Cargo
        /// </summary>
        [DataMember(Name = "cargo", IsRequired = true, EmitDefaultValue = true)]
        public ShipCargo Cargo { get; set; }

        /// <summary>
        /// Gets or Sets Fuel
        /// </summary>
        [DataMember(Name = "fuel", IsRequired = true, EmitDefaultValue = true)]
        public ShipFuel Fuel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Ship {\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("  Registration: ").Append(Registration).Append("\n");
            sb.Append("  Nav: ").Append(Nav).Append("\n");
            sb.Append("  Crew: ").Append(Crew).Append("\n");
            sb.Append("  Frame: ").Append(Frame).Append("\n");
            sb.Append("  Reactor: ").Append(Reactor).Append("\n");
            sb.Append("  Engine: ").Append(Engine).Append("\n");
            sb.Append("  Cooldown: ").Append(Cooldown).Append("\n");
            sb.Append("  Modules: ").Append(Modules).Append("\n");
            sb.Append("  Mounts: ").Append(Mounts).Append("\n");
            sb.Append("  Cargo: ").Append(Cargo).Append("\n");
            sb.Append("  Fuel: ").Append(Fuel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
