/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = SpaceTraders.Generated.Client.OpenAPIDateConverter;

namespace SpaceTraders.Generated.Model
{
    /// <summary>
    /// The reactor of the ship. The reactor is responsible for powering the ship&#39;s systems and weapons.
    /// </summary>
    [DataContract(Name = "ShipReactor")]
    public partial class ShipReactor
    {
        /// <summary>
        /// Symbol of the reactor.
        /// </summary>
        /// <value>Symbol of the reactor.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SymbolEnum
        {
            /// <summary>
            /// Enum REACTORSOLARI for value: REACTOR_SOLAR_I
            /// </summary>
            [EnumMember(Value = "REACTOR_SOLAR_I")]
            REACTORSOLARI = 1,

            /// <summary>
            /// Enum REACTORFUSIONI for value: REACTOR_FUSION_I
            /// </summary>
            [EnumMember(Value = "REACTOR_FUSION_I")]
            REACTORFUSIONI = 2,

            /// <summary>
            /// Enum REACTORFISSIONI for value: REACTOR_FISSION_I
            /// </summary>
            [EnumMember(Value = "REACTOR_FISSION_I")]
            REACTORFISSIONI = 3,

            /// <summary>
            /// Enum REACTORCHEMICALI for value: REACTOR_CHEMICAL_I
            /// </summary>
            [EnumMember(Value = "REACTOR_CHEMICAL_I")]
            REACTORCHEMICALI = 4,

            /// <summary>
            /// Enum REACTORANTIMATTERI for value: REACTOR_ANTIMATTER_I
            /// </summary>
            [EnumMember(Value = "REACTOR_ANTIMATTER_I")]
            REACTORANTIMATTERI = 5
        }


        /// <summary>
        /// Symbol of the reactor.
        /// </summary>
        /// <value>Symbol of the reactor.</value>
        [DataMember(Name = "symbol", IsRequired = true, EmitDefaultValue = true)]
        public SymbolEnum Symbol { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ShipReactor" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ShipReactor() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ShipReactor" /> class.
        /// </summary>
        /// <param name="symbol">Symbol of the reactor. (required).</param>
        /// <param name="name">Name of the reactor. (required).</param>
        /// <param name="description">Description of the reactor. (required).</param>
        /// <param name="condition">The repairable condition of a component. A value of 0 indicates the component needs significant repairs, while a value of 1 indicates the component is in near perfect condition. As the condition of a component is repaired, the overall integrity of the component decreases. (required).</param>
        /// <param name="integrity">The overall integrity of the component, which determines the performance of the component. A value of 0 indicates that the component is almost completely degraded, while a value of 1 indicates that the component is in near perfect condition. The integrity of the component is non-repairable, and represents permanent wear over time. (required).</param>
        /// <param name="powerOutput">The amount of power provided by this reactor. The more power a reactor provides to the ship, the lower the cooldown it gets when using a module or mount that taxes the ship&#39;s power. (required).</param>
        /// <param name="requirements">requirements (required).</param>
        /// <param name="quality">The overall quality of the component, which determines the quality of the component. High quality components return more ships parts and ship plating when a ship is scrapped. But also require more of these parts to repair. This is transparent to the player, as the parts are bought from/sold to the marketplace. (required).</param>
        public ShipReactor(SymbolEnum symbol = default, string name = default, string description = default, double condition = default, double integrity = default, int powerOutput = default, ShipRequirements requirements = default, decimal quality = default)
        {
            this.Symbol = symbol;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ShipReactor and cannot be null");
            }
            this.Name = name;
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new ArgumentNullException("description is a required property for ShipReactor and cannot be null");
            }
            this.Description = description;
            this.Condition = condition;
            this.Integrity = integrity;
            this.PowerOutput = powerOutput;
            // to ensure "requirements" is required (not null)
            if (requirements == null)
            {
                throw new ArgumentNullException("requirements is a required property for ShipReactor and cannot be null");
            }
            this.Requirements = requirements;
            this.Quality = quality;
        }

        /// <summary>
        /// Name of the reactor.
        /// </summary>
        /// <value>Name of the reactor.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Description of the reactor.
        /// </summary>
        /// <value>Description of the reactor.</value>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// The repairable condition of a component. A value of 0 indicates the component needs significant repairs, while a value of 1 indicates the component is in near perfect condition. As the condition of a component is repaired, the overall integrity of the component decreases.
        /// </summary>
        /// <value>The repairable condition of a component. A value of 0 indicates the component needs significant repairs, while a value of 1 indicates the component is in near perfect condition. As the condition of a component is repaired, the overall integrity of the component decreases.</value>
        [DataMember(Name = "condition", IsRequired = true, EmitDefaultValue = true)]
        public double Condition { get; set; }

        /// <summary>
        /// The overall integrity of the component, which determines the performance of the component. A value of 0 indicates that the component is almost completely degraded, while a value of 1 indicates that the component is in near perfect condition. The integrity of the component is non-repairable, and represents permanent wear over time.
        /// </summary>
        /// <value>The overall integrity of the component, which determines the performance of the component. A value of 0 indicates that the component is almost completely degraded, while a value of 1 indicates that the component is in near perfect condition. The integrity of the component is non-repairable, and represents permanent wear over time.</value>
        [DataMember(Name = "integrity", IsRequired = true, EmitDefaultValue = true)]
        public double Integrity { get; set; }

        /// <summary>
        /// The amount of power provided by this reactor. The more power a reactor provides to the ship, the lower the cooldown it gets when using a module or mount that taxes the ship&#39;s power.
        /// </summary>
        /// <value>The amount of power provided by this reactor. The more power a reactor provides to the ship, the lower the cooldown it gets when using a module or mount that taxes the ship&#39;s power.</value>
        [DataMember(Name = "powerOutput", IsRequired = true, EmitDefaultValue = true)]
        public int PowerOutput { get; set; }

        /// <summary>
        /// Gets or Sets Requirements
        /// </summary>
        [DataMember(Name = "requirements", IsRequired = true, EmitDefaultValue = true)]
        public ShipRequirements Requirements { get; set; }

        /// <summary>
        /// The overall quality of the component, which determines the quality of the component. High quality components return more ships parts and ship plating when a ship is scrapped. But also require more of these parts to repair. This is transparent to the player, as the parts are bought from/sold to the marketplace.
        /// </summary>
        /// <value>The overall quality of the component, which determines the quality of the component. High quality components return more ships parts and ship plating when a ship is scrapped. But also require more of these parts to repair. This is transparent to the player, as the parts are bought from/sold to the marketplace.</value>
        [DataMember(Name = "quality", IsRequired = true, EmitDefaultValue = true)]
        public decimal Quality { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ShipReactor {\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Condition: ").Append(Condition).Append("\n");
            sb.Append("  Integrity: ").Append(Integrity).Append("\n");
            sb.Append("  PowerOutput: ").Append(PowerOutput).Append("\n");
            sb.Append("  Requirements: ").Append(Requirements).Append("\n");
            sb.Append("  Quality: ").Append(Quality).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
