/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = SpaceTraders.Generated.Client.OpenAPIDateConverter;

namespace SpaceTraders.Generated.Model
{
    /// <summary>
    /// The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.
    /// </summary>
    [DataContract(Name = "ShipFrame")]
    public partial class ShipFrame
    {
        /// <summary>
        /// Symbol of the frame.
        /// </summary>
        /// <value>Symbol of the frame.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SymbolEnum
        {
            /// <summary>
            /// Enum FRAMEPROBE for value: FRAME_PROBE
            /// </summary>
            [EnumMember(Value = "FRAME_PROBE")]
            FRAMEPROBE = 1,

            /// <summary>
            /// Enum FRAMEDRONE for value: FRAME_DRONE
            /// </summary>
            [EnumMember(Value = "FRAME_DRONE")]
            FRAMEDRONE = 2,

            /// <summary>
            /// Enum FRAMEINTERCEPTOR for value: FRAME_INTERCEPTOR
            /// </summary>
            [EnumMember(Value = "FRAME_INTERCEPTOR")]
            FRAMEINTERCEPTOR = 3,

            /// <summary>
            /// Enum FRAMERACER for value: FRAME_RACER
            /// </summary>
            [EnumMember(Value = "FRAME_RACER")]
            FRAMERACER = 4,

            /// <summary>
            /// Enum FRAMEFIGHTER for value: FRAME_FIGHTER
            /// </summary>
            [EnumMember(Value = "FRAME_FIGHTER")]
            FRAMEFIGHTER = 5,

            /// <summary>
            /// Enum FRAMEFRIGATE for value: FRAME_FRIGATE
            /// </summary>
            [EnumMember(Value = "FRAME_FRIGATE")]
            FRAMEFRIGATE = 6,

            /// <summary>
            /// Enum FRAMESHUTTLE for value: FRAME_SHUTTLE
            /// </summary>
            [EnumMember(Value = "FRAME_SHUTTLE")]
            FRAMESHUTTLE = 7,

            /// <summary>
            /// Enum FRAMEEXPLORER for value: FRAME_EXPLORER
            /// </summary>
            [EnumMember(Value = "FRAME_EXPLORER")]
            FRAMEEXPLORER = 8,

            /// <summary>
            /// Enum FRAMEMINER for value: FRAME_MINER
            /// </summary>
            [EnumMember(Value = "FRAME_MINER")]
            FRAMEMINER = 9,

            /// <summary>
            /// Enum FRAMELIGHTFREIGHTER for value: FRAME_LIGHT_FREIGHTER
            /// </summary>
            [EnumMember(Value = "FRAME_LIGHT_FREIGHTER")]
            FRAMELIGHTFREIGHTER = 10,

            /// <summary>
            /// Enum FRAMEHEAVYFREIGHTER for value: FRAME_HEAVY_FREIGHTER
            /// </summary>
            [EnumMember(Value = "FRAME_HEAVY_FREIGHTER")]
            FRAMEHEAVYFREIGHTER = 11,

            /// <summary>
            /// Enum FRAMETRANSPORT for value: FRAME_TRANSPORT
            /// </summary>
            [EnumMember(Value = "FRAME_TRANSPORT")]
            FRAMETRANSPORT = 12,

            /// <summary>
            /// Enum FRAMEDESTROYER for value: FRAME_DESTROYER
            /// </summary>
            [EnumMember(Value = "FRAME_DESTROYER")]
            FRAMEDESTROYER = 13,

            /// <summary>
            /// Enum FRAMECRUISER for value: FRAME_CRUISER
            /// </summary>
            [EnumMember(Value = "FRAME_CRUISER")]
            FRAMECRUISER = 14,

            /// <summary>
            /// Enum FRAMECARRIER for value: FRAME_CARRIER
            /// </summary>
            [EnumMember(Value = "FRAME_CARRIER")]
            FRAMECARRIER = 15,

            /// <summary>
            /// Enum FRAMEBULKFREIGHTER for value: FRAME_BULK_FREIGHTER
            /// </summary>
            [EnumMember(Value = "FRAME_BULK_FREIGHTER")]
            FRAMEBULKFREIGHTER = 16
        }


        /// <summary>
        /// Symbol of the frame.
        /// </summary>
        /// <value>Symbol of the frame.</value>
        [DataMember(Name = "symbol", IsRequired = true, EmitDefaultValue = true)]
        public SymbolEnum Symbol { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ShipFrame" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ShipFrame() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ShipFrame" /> class.
        /// </summary>
        /// <param name="symbol">Symbol of the frame. (required).</param>
        /// <param name="name">Name of the frame. (required).</param>
        /// <param name="description">Description of the frame. (required).</param>
        /// <param name="condition">The repairable condition of a component. A value of 0 indicates the component needs significant repairs, while a value of 1 indicates the component is in near perfect condition. As the condition of a component is repaired, the overall integrity of the component decreases. (required).</param>
        /// <param name="integrity">The overall integrity of the component, which determines the performance of the component. A value of 0 indicates that the component is almost completely degraded, while a value of 1 indicates that the component is in near perfect condition. The integrity of the component is non-repairable, and represents permanent wear over time. (required).</param>
        /// <param name="moduleSlots">The amount of slots that can be dedicated to modules installed in the ship. Each installed module take up a number of slots, and once there are no more slots, no new modules can be installed. (required).</param>
        /// <param name="mountingPoints">The amount of slots that can be dedicated to mounts installed in the ship. Each installed mount takes up a number of points, and once there are no more points remaining, no new mounts can be installed. (required).</param>
        /// <param name="fuelCapacity">The maximum amount of fuel that can be stored in this ship. When refueling, the ship will be refueled to this amount. (required).</param>
        /// <param name="requirements">requirements (required).</param>
        /// <param name="quality">The overall quality of the component, which determines the quality of the component. High quality components return more ships parts and ship plating when a ship is scrapped. But also require more of these parts to repair. This is transparent to the player, as the parts are bought from/sold to the marketplace. (required).</param>
        public ShipFrame(SymbolEnum symbol = default, string name = default, string description = default, double condition = default, double integrity = default, int moduleSlots = default, int mountingPoints = default, int fuelCapacity = default, ShipRequirements requirements = default, decimal quality = default)
        {
            this.Symbol = symbol;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ShipFrame and cannot be null");
            }
            this.Name = name;
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new ArgumentNullException("description is a required property for ShipFrame and cannot be null");
            }
            this.Description = description;
            this.Condition = condition;
            this.Integrity = integrity;
            this.ModuleSlots = moduleSlots;
            this.MountingPoints = mountingPoints;
            this.FuelCapacity = fuelCapacity;
            // to ensure "requirements" is required (not null)
            if (requirements == null)
            {
                throw new ArgumentNullException("requirements is a required property for ShipFrame and cannot be null");
            }
            this.Requirements = requirements;
            this.Quality = quality;
        }

        /// <summary>
        /// Name of the frame.
        /// </summary>
        /// <value>Name of the frame.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Description of the frame.
        /// </summary>
        /// <value>Description of the frame.</value>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// The repairable condition of a component. A value of 0 indicates the component needs significant repairs, while a value of 1 indicates the component is in near perfect condition. As the condition of a component is repaired, the overall integrity of the component decreases.
        /// </summary>
        /// <value>The repairable condition of a component. A value of 0 indicates the component needs significant repairs, while a value of 1 indicates the component is in near perfect condition. As the condition of a component is repaired, the overall integrity of the component decreases.</value>
        [DataMember(Name = "condition", IsRequired = true, EmitDefaultValue = true)]
        public double Condition { get; set; }

        /// <summary>
        /// The overall integrity of the component, which determines the performance of the component. A value of 0 indicates that the component is almost completely degraded, while a value of 1 indicates that the component is in near perfect condition. The integrity of the component is non-repairable, and represents permanent wear over time.
        /// </summary>
        /// <value>The overall integrity of the component, which determines the performance of the component. A value of 0 indicates that the component is almost completely degraded, while a value of 1 indicates that the component is in near perfect condition. The integrity of the component is non-repairable, and represents permanent wear over time.</value>
        [DataMember(Name = "integrity", IsRequired = true, EmitDefaultValue = true)]
        public double Integrity { get; set; }

        /// <summary>
        /// The amount of slots that can be dedicated to modules installed in the ship. Each installed module take up a number of slots, and once there are no more slots, no new modules can be installed.
        /// </summary>
        /// <value>The amount of slots that can be dedicated to modules installed in the ship. Each installed module take up a number of slots, and once there are no more slots, no new modules can be installed.</value>
        [DataMember(Name = "moduleSlots", IsRequired = true, EmitDefaultValue = true)]
        public int ModuleSlots { get; set; }

        /// <summary>
        /// The amount of slots that can be dedicated to mounts installed in the ship. Each installed mount takes up a number of points, and once there are no more points remaining, no new mounts can be installed.
        /// </summary>
        /// <value>The amount of slots that can be dedicated to mounts installed in the ship. Each installed mount takes up a number of points, and once there are no more points remaining, no new mounts can be installed.</value>
        [DataMember(Name = "mountingPoints", IsRequired = true, EmitDefaultValue = true)]
        public int MountingPoints { get; set; }

        /// <summary>
        /// The maximum amount of fuel that can be stored in this ship. When refueling, the ship will be refueled to this amount.
        /// </summary>
        /// <value>The maximum amount of fuel that can be stored in this ship. When refueling, the ship will be refueled to this amount.</value>
        [DataMember(Name = "fuelCapacity", IsRequired = true, EmitDefaultValue = true)]
        public int FuelCapacity { get; set; }

        /// <summary>
        /// Gets or Sets Requirements
        /// </summary>
        [DataMember(Name = "requirements", IsRequired = true, EmitDefaultValue = true)]
        public ShipRequirements Requirements { get; set; }

        /// <summary>
        /// The overall quality of the component, which determines the quality of the component. High quality components return more ships parts and ship plating when a ship is scrapped. But also require more of these parts to repair. This is transparent to the player, as the parts are bought from/sold to the marketplace.
        /// </summary>
        /// <value>The overall quality of the component, which determines the quality of the component. High quality components return more ships parts and ship plating when a ship is scrapped. But also require more of these parts to repair. This is transparent to the player, as the parts are bought from/sold to the marketplace.</value>
        [DataMember(Name = "quality", IsRequired = true, EmitDefaultValue = true)]
        public decimal Quality { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ShipFrame {\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Condition: ").Append(Condition).Append("\n");
            sb.Append("  Integrity: ").Append(Integrity).Append("\n");
            sb.Append("  ModuleSlots: ").Append(ModuleSlots).Append("\n");
            sb.Append("  MountingPoints: ").Append(MountingPoints).Append("\n");
            sb.Append("  FuelCapacity: ").Append(FuelCapacity).Append("\n");
            sb.Append("  Requirements: ").Append(Requirements).Append("\n");
            sb.Append("  Quality: ").Append(Quality).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
