/*
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = SpaceTraders.Generated.Client.OpenAPIDateConverter;

namespace SpaceTraders.Generated.Model
{
    /// <summary>
    /// SiphonResources201ResponseData
    /// </summary>
    [DataContract(Name = "siphon_resources_201_response_data")]
    public partial class SiphonResources201ResponseData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SiphonResources201ResponseData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SiphonResources201ResponseData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SiphonResources201ResponseData" /> class.
        /// </summary>
        /// <param name="cooldown">cooldown (required).</param>
        /// <param name="siphon">siphon (required).</param>
        /// <param name="cargo">cargo (required).</param>
        /// <param name="events">events (required).</param>
        public SiphonResources201ResponseData(Cooldown cooldown = default, Siphon siphon = default, ShipCargo cargo = default, List<ShipConditionEvent> events = default)
        {
            // to ensure "cooldown" is required (not null)
            if (cooldown == null)
            {
                throw new ArgumentNullException("cooldown is a required property for SiphonResources201ResponseData and cannot be null");
            }
            this.Cooldown = cooldown;
            // to ensure "siphon" is required (not null)
            if (siphon == null)
            {
                throw new ArgumentNullException("siphon is a required property for SiphonResources201ResponseData and cannot be null");
            }
            this.Siphon = siphon;
            // to ensure "cargo" is required (not null)
            if (cargo == null)
            {
                throw new ArgumentNullException("cargo is a required property for SiphonResources201ResponseData and cannot be null");
            }
            this.Cargo = cargo;
            // to ensure "events" is required (not null)
            if (events == null)
            {
                throw new ArgumentNullException("events is a required property for SiphonResources201ResponseData and cannot be null");
            }
            this.Events = events;
        }

        /// <summary>
        /// Gets or Sets Cooldown
        /// </summary>
        [DataMember(Name = "cooldown", IsRequired = true, EmitDefaultValue = true)]
        public Cooldown Cooldown { get; set; }

        /// <summary>
        /// Gets or Sets Siphon
        /// </summary>
        [DataMember(Name = "siphon", IsRequired = true, EmitDefaultValue = true)]
        public Siphon Siphon { get; set; }

        /// <summary>
        /// Gets or Sets Cargo
        /// </summary>
        [DataMember(Name = "cargo", IsRequired = true, EmitDefaultValue = true)]
        public ShipCargo Cargo { get; set; }

        /// <summary>
        /// Gets or Sets Events
        /// </summary>
        [DataMember(Name = "events", IsRequired = true, EmitDefaultValue = true)]
        public List<ShipConditionEvent> Events { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SiphonResources201ResponseData {\n");
            sb.Append("  Cooldown: ").Append(Cooldown).Append("\n");
            sb.Append("  Siphon: ").Append(Siphon).Append("\n");
            sb.Append("  Cargo: ").Append(Cargo).Append("\n");
            sb.Append("  Events: ").Append(Events).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
